<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.two_factor.provider' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\scheb\\two-factor-bundle\\Security\\TwoFactor\\Provider\\TwoFactorProviderInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\TwoFactor\\Provider.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\TwoFactor\\Authenticator.php';

return $this->privates['contao.security.two_factor.provider'] = new \Contao\CoreBundle\Security\TwoFactor\Provider(($this->services['contao.security.two_factor.authenticator'] ?? ($this->services['contao.security.two_factor.authenticator'] = new \Contao\CoreBundle\Security\TwoFactor\Authenticator())));
