<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'contao.security.authentication_failure_handler' shared service.

include_once \dirname(__DIR__, 4).'\\vendor\\symfony\\security-http\\Authentication\\AuthenticationFailureHandlerInterface.php';
include_once \dirname(__DIR__, 4).'\\vendor\\contao\\core-bundle\\src\\Security\\Authentication\\AuthenticationFailureHandler.php';

return $this->privates['contao.security.authentication_failure_handler'] = new \Contao\CoreBundle\Security\Authentication\AuthenticationFailureHandler(($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
